default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
  port: 3306
  variables:
    time_zone: Asia/Tokyo
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: kokinoue_development

test:
  <<: *default
  database: kokinoue_test

production:
  <<: *default
  host: <%= ENV.fetch("PRD_HOST") %>
  database: <%= ENV.fetch("PRD_DATABASE") %>
  username: <%= ENV.fetch("PRD_USERNAME") %>
  password: <%= ENV.fetch("PRD_PASSWORD") %>
